# Generated by Django 5.0.2 on 2024-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogconfig',
            name='is_oauthed',
        ),
        migrations.AddField(
            model_name='blogconfig',
            name='ion_username',
            field=models.TextField(default='No Username'),
            preserve_default=False,
        ),
    ]
