# Generated by Django 5.0.2 on 2024-03-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogauth', '0002_remove_blogconfig_is_oauthed_blogconfig_ion_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogConfig',
            new_name='IonUser',
        ),
    ]
